### ISSUE TITLE
Incorporate tutorials from my personal blog

### ISSUE THREAD

**Issue by yiakwy** [grpc/proposal#42]
I have addressed some hard problems hardly tracked by grpc group in my personal blog. Here is the relevant article: https://yiakwy.github.io/blog/2017/10/01/gRPC-C-CORE. Feel free to assemble it in.

**Comment by mehrdada** [comment]
I think a good place to announce this would be through a post on [the grpc-io mailing list](https://groups.google.com/forum/#!forum/grpc-io).
